### ISSUE TITLE
[BLS] Signing changes upstream

### ISSUE THREAD

**Issue by mratsim** [status-im/nim-beacon-chain#294]
The BLS test vectors changed expected result between 0.6.1 and 0.6.2 tests:

0.6.1 (May 5) - https://github.com/ethereum/eth2.0-spec-tests/commit/161a36ee6232d8d251d798c8262638ed0c34c9c6
```yaml
test_cases:
- input: {privkey: '0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3',
    message: '0x0000000000000000000000000000000000000000000000000000000000000000',
    domain: '0x00'}
  output: '0xb2cc74bc9f089ed9764bbceac5edba416bef5e73701288977b9cac1ccb6964269d4ebf78b4e8aa7792ba09d3e49c8e6a1351bdf582971f796bbaf6320e81251c9d28f674d720cca07ed14596b96697cf18238e0e03ebd7fc1353d885a39407e0'
- input: {privkey: '0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3',
    message: '0x0000000000000000000000000000000000000000000000000000000000000000',
    domain: '0x01'}
  output: '0xa9f1e4d2b22d0a9119c70bab8597a47135b761f3852d978e61a8fa72867a06bd9a884f1ec57733013a4e244cfea30c420d3ff86651cf8dfd341c3dcb7441e949167387aee50a085d0a9ddeaee1540409a268e5698fb1daa2a552deaddb2d3528'
- input: {privkey: '0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3',
    message: '0x0000000000000000000000000000000000000000000000000000000000000000',
    domain: '0x04d2'}
  output: '0xaa005163ec85b882c16bbb52b8bb4c0071cb9375c655370d37433ca660f0944ed85ba390d515f89789a5432b7fb8c4d409f83478064ee06f0fb3900203b665192318e836e3920e25dc3ed8127143441c215f2ef5fba7ab8a5769296456269b2e'
```

0.6.2 (May 28) - https://github.com/ethereum/eth2.0-spec-tests/commit/cfc6e3c91d781f0dfe493ceb548391f5e88e54c7
```yaml
test_cases:
- input: {privkey: '0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3',
    message: '0x0000000000000000000000000000000000000000000000000000000000000000',
    domain: '0x00'}
  output: '0x97004641c3f3c9973e5d5064578e7b87230655905546f5e95469dfa41cfae49f3741112cdf425f8a3f9d0fdde2f4980516b1fd6748d87a234589f065145cfe9c697cc6a61211c9322ad4c279c20b8d943c8c2f1dd13fc0418cb2dac4d0a9e34d'
- input: {privkey: '0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3',
    message: '0x0000000000000000000000000000000000000000000000000000000000000000',
    domain: '0x01'}
  output: '0xb3c8a46899cdae13388282c98b1835193989f871aba9b9b68d964544fee2d8ac7eea900730f4e72076dc646a308b37d216e051a1286bdd0857152316082c7e8baccf41327b1a4e40fb286dd6d8a812cd80d91bf613186b154e4f3e481ac73400'
- input: {privkey: '0x263dbd792f5b1be47ed85f8938c0f29586af0d3ac7b977f21c278fe1462040e3',
    message: '0x0000000000000000000000000000000000000000000000000000000000000000',
    domain: '0x04d2'}
  output: '0xb1003b46a22cd9e72c208a4b7f34ebb5c5b4f17c69743e61c33f56c5f5f8f07fc1bb25b2e36dd9e3b2972e804e56f4ac16b32964080272a5ed42f94df44b02dd0a48ed60cc899494c8ab9b8e159aadb8394eebfd3a62a6d9f1f35aee58c4fa0b'
```

This is blocking #293.

There are couple of recent unrelated BLS changes like https://github.com/ethereum/eth2.0-spec-tests/issues/3.

I expect the issue is related to the hash function change in the python BLS library https://github.com/ethereum/py_ecc/pull/70
