### ISSUE TITLE
Error writting to data dir volume

### ISSUE THREAD

**Issue by cbermudez97** [status-im/nim-beacon-chain#3700]
**Describe the bug**
Im running a beacon node using docker compose while persisting the node data to a volume. When started the node fail after some errors about permissions for the data dir I used. First my data folder has 755 as permissions. When starting the node it fails with these:

```
cl-beacon-nimbus  | [Chronicles] Log message not delivered: [Chronicles] A writer was not configured for a dynamic log output device. Log message not delivered: WRN 2022-06-03 15:33:16.602+00:00 Data directory has insecure permissions. Correcting them. data_dir=/data current_permissions=0755 required_permissions=0700
```

Following the instructions there I changed my data folder permissions to 700. Running the node again shows these then:
```cl-beacon-nimbus  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(445) main
cl-beacon-nimbus  | /home/user/nimbus-eth2/vendor/nim-libp2p/libp2p/stream/bufferstream.nim(438) NimMain
cl-beacon-nimbus  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(2069) main
cl-beacon-nimbus  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1937) handleStartUpCmd
cl-beacon-nimbus  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1690) doRunBeaconNode
cl-beacon-nimbus  | /home/user/nimbus-eth2/beacon_chain/nimbus_beacon_node.nim(1503) createPidFile
cl-beacon-nimbus  | /home/user/nimbus-eth2/vendor/nimbus-build-system/vendor/Nim/lib/system/io.nim(706) writeFile
cl-beacon-nimbus  | Error: unhandled exception: cannot open: /data/beacon_node.pid [IOError]
cl-beacon-nimbus exited with code 1
```

**To Reproduce**
1. Create `docker-compose.yml` with:
```yaml
version: '3.9'
services:
  beacon:
    stop_grace_period: 30s
    container_name: cl-beacon-nimbus
    restart: unless-stopped
    image: statusim/nimbus-eth2:amd64-latest
    volumes:
      - ./data:/data         
      - ./jwtsecret:/tmp/jwt/jwtsecret
    ports:
      - 9000:9000/tcp
      - 9000:9000/udp
      - 5054:5054/tcp
    expose:
      - 5051
    command:
      - --network=merge-testnets/kiln
      - --data-dir=/data
      - --tcp-port=9000
      - --udp-port=9000
      - --web3-url=ws://127.0.0.1:8151
      - --max-peers=50
      - --rest
      - --rest-address=0.0.0.0
      - --rest-port=5051
      - --rest-allow-origin=*
      - --metrics
      - --metrics-address=0.0.0.0
      - --metrics-port=5054
      - --jwt-secret="/tmp/jwt/jwtsecret"
      - --terminal-total-difficulty-override=100000000000000000000000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
```
2. Run `openssl rand -hex 32 > jwtsecret`
3. Create `./data` and change its permissions to 755
4. Run `docker compose up beacon`
5. Change `./data` permissions to 700
6. Run `docker compose up beacon`

**Additional**
All the above commands were used as root.
