### ISSUE TITLE
Trouble parsing trustedNodeSync via toml

### ISSUE THREAD

**Issue by icculp** [status-im/nim-beacon-chain#4413]
**Describe the bug**
trustedNodeSync and trusted-node-url not being read in via toml file, which I discovered during my work to integrate Nimbus  for eth2 validation here https://github.com/decentralized-authority/node-launcher/issues/70. 

**To Reproduce**
The flags fail to read in, and worse yet the node will fail to start if the flags aren't at the bottom. When the flags aren't at the bottom the node will fail to start and spit out an error about failing to read whatever the next flag in line would be, like:
/var/lib/config/nimbus.toml(14, 13) Unexpected field 'jwt-secret' while deserializing 'trustedNodeSync'

Tried the flags like 
[trustedNodeSync]
trusted-node-url = "url"

as well as variations like:
trustedNodeSync = true
trusted-node-url = "url"

and 

trustedNodeSync.trusted-node-url = "url"

I discovered that the only way to get the node to start was to put the flags in at the bottom. However, even then the node wasn't recognizing the flag and started syncing from 0.

**Comment by zah** [comment]
I was able to execute trusted node sync successfully with the following config:

```toml
data-dir = "data/mainnet"
network = "mainnet"

[trustedNodeSync]
backfill = false
trusted-node-url = "http://testing.mainnet.beacon-api.nimbus.team/"
```

I launched the client like this:

```bash
nimbus_beacon_node trustedNodeSync --config-file=config.toml
```

**Comment by zah** [comment]
Please note that the TOML format is not whitespace sensitive, so when you create the following config:

```toml
[trustedNodeSync]
backfill = false

jwt-secret = "..."
```

... the TOML specification dictates that the `jwt-secret` property is nested under `trustedNodeSync` which is not correct from the perspective of Nimbus, because `jwt-secret` is a top-level property of the configuration. The Nimbus `--help` screen will help you determine where each configuration property is nested.
