### ISSUE TITLE
Check content-type and return 415 if not supported by route

### ISSUE THREAD

**Issue by nflaig** [status-im/nim-beacon-chain#6321]
**Describe the bug**

Noticed that Nimbus BN does not check the content type of the request body and just tries to deserialize it, causing strange errors.

E.g. Error on Lodestar when trying to call `getAttesterDuties` with SSZ request body 
```
[vc-06-geth-nimbus-lodestar] May-28 22:37:20.092[]                error: Failed to download attester duties epoch=0 - getAttesterDuties failed with status 400: Invalid validator's index value(s)
[vc-06-geth-nimbus-lodestar] Error: getAttesterDuties failed with status 400: Invalid validator's index value(s)
```

As per spec, this route does not require to support SSZ request bodies and by default Lodestar will be using JSON but it would still be nice if Nimbus could return a 415 error as this would allow to gradually support SSZ for more routes as the client can retry the request with JSON body and cache for this route that SSZ is not supported, only sending JSON in subsequent requests.

**To Reproduce**

I've been using Kurtosis to run the tests (with custom lodestar image)
```yaml
participants:
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: lodestar
    cl_image: nflaig/lodestar:ssz-api
    vc_type: nimbus
    vc_image: statusim/nimbus-validator-client:amd64-latest
    vc_extra_params:
      - --doppelganger-detection=off
    count: 1
  - el_type: geth
    el_image: ethereum/client-go:stable
    cl_type: nimbus
    cl_image: statusim/nimbus-eth2:amd64-latest
    vc_type: lodestar
    vc_image: nflaig/lodestar:ssz-api
    count: 1
```
