### ISSUE TITLE
Checkpoint sync fails with "Attempt to download checkpoint state timed out" on  holesky on all endpoints

### ISSUE THREAD

**Issue by ibhagwan** [status-im/nim-beacon-chain#6333]
**Describe the bug**
Unable to checkpoint sync on holesky, all EPs fail with the error `Attempt to download checkpoint state timed out`, doesn't seem like I have a connection issue as I can `curl` the EPs as shown in the screenshot below

**To Reproduce**
1. Platform details (OS, architecture): Void Linux
2. Branch/commit used: imbus beacon node v24.5.1-d2a075-stateofus
3. Commands being executed:
> `run-trusted.sh`
```sh
#!/bin/sh
sudo -u nimbus sh -c '/usr/local/bin/nimbus_beacon_node trustedNodeSync --config-file=/var/lib/nimbus/holesky/config-trusted.toml'
```
> `config-trusted.toml`
> Tried with all EPs below
```toml
network = "holesky"
data-dir = "/data/nimbus/holesky/beacon"

[trustedNodeSync]
backfill = false
# trusted-node-url = "https://holesky.beaconstate.info"
# trusted-node-url = "https://beaconstate-holesky.chainsafe.io"
# trusted-node-url = "https://holesky.beaconstate.ethstaker.cc"
# trusted-node-url = "https://checkpoint-sync.holesky.ethpandaops.io"
trusted-node-url = "https://holesky-checkpoint-sync.stakely.io"
```
5. Relevant log lines:
```
INF 2024-06-08 12:27:49.488-07:00 Obtaining genesis state                    topics="beacnde" sourceUrl=https://github.com/status-im/nimbus-eth2/releases/download/v23.9.1/holesky-genesis.ssz.sz
NTC 2024-06-08 12:29:04.122-07:00 Starting trusted node sync                 databaseDir=/data/nimbus/holesky/beacon/db backfill=false reindex=false syncTarget=finalized restUrl=https://holesky.beaconstate.info
NTC 2024-06-08 12:29:04.517-07:00 Downloading checkpoint state               syncTarget=finalized restUrl=https://holesky.beaconstate.info stateId=finalized
ERR 2024-06-08 12:30:04.519-07:00 Attempt to download checkpoint state timed out syncTarget=finalized restUrl=https://holesky.beaconstate.info stateId=finalized
```

**Screenshots**
![image](https://github.com/status-im/nimbus-eth2/assets/59988195/13d8ef24-87bc-4820-ae16-c93fbbc3155c)

**Additional context**
This same machine used to work before (since holesky genesis), it was down for a while so I removed the DB and attempted checkpoint sync.
